// AUTO-GENERATED by scripts/genpuzzles.ts — do not edit by hand.
// Regenerate: npx tsx scripts/genpuzzles.ts --games 160 --depth 6 --verify 4 --target 80 --seed 12345
// Or, from the checked-in shards in data/puzzle-shards/ and without re-mining:
//   npx tsx scripts/genpuzzles.ts --merge
// 161 puzzles (regicide: 13, escape: 0, crushing: 146, advantage: 2), 0 truncated, 39.9% of 404 candidates.
// By band: easy: 106, medium: 22, hard: 29, ollamh: 4.
// By primary motif, zeros included (ADR-0003): guillotine: 0, snapTrap: 0, clamp: 0, spring: 0, balling: 0, cordon: 0, cornerFight: 7, twinTowers: 0,
// none: 154.
// Format: one line per puzzle, `id|pos|leadIn|line|goal|flags|dtm|depthToFind|salience|motif|tags`
// — see src/game/puzzleBank.ts for the exact contract.

/** Gameplay-flag fingerprint of the ruleset every line here was verified under
 *  (empty ⇒ no bank). A Puzzle belongs to exactly one ruleset and is invalid
 *  under any other, so the loader serves an exact match and nothing else.
 *  Typed `string` (not the literal) so the loader's guard stays a real
 *  comparison. */
export const BANK_RULES_FINGERPRINT: string =
  "armedKing=true;cornersHostile=true;encirclementWin=true;kingMayReoccupyThrone=true;repetitionResult=loss_for_defenders;shieldwallCapture=false;soldiersPassThroughThrone=true;strongKingAdjacentToThrone=true;strongKingOnThrone=true;throneHostileToKing=true;throneHostileToSoldiers=true";

/** The board these positions were verified on. The field exists so a future 9×9
 *  fork inherits the format unchanged; the engine is deliberately NOT
 *  generalised, and `BOARD_SIZE` stays a const. */
export const BANK_BOARD_SIZE: number = 7;

/** The depth `npm test` re-checks uniqueness at. Low on purpose: the generator
 *  holds the strong claim, and re-running the generation-depth search over every
 *  solver move in the fast suite would add another `ai.test.ts`. Every shipped
 *  solving move is uniquely best here as well as at the generation depth,
 *  because the generator rejects the ones that are not. */
export const BANK_VERIFY_DEPTH: number = 4;

export const BANK_DATA: string = `00001|3A3/A6/7/AA1KDA1/3A2D/2D4/4A2 a|0305|3303|crushing||-|1|kt||defenders,moves1
00002|3A3/A6/7/AA1K1A1/2D1D1D/7/4A2 a|6454|3363|crushing||-|1|kt||defenders,moves1
00003|3A3/A6/7/AADK1A1/4D1D/4A2/7 a|3151|3363|crushing||-|1|kt||defenders,moves1
00004|3A3/A6/3AK2/D4A1/6D/DA2A2/7 a|3531|2404|crushing||-|1|kt||defenders,moves1
00005|2A4/3A3/2D4/AADK2A/3D3/3A3/3AD2 a|0212|3335|crushing||-|3|kt||defenders,moves1
00006|7/4AA1/2D4/AADK2A/1D5/5A1/3AD2 a|3656|3303|crushing||-|1|kt||defenders,moves1
00007|2AKDA1/1A1A2D/2A1A1D/6A/7/7/7 d|1615|2425|crushing||-|1|ct||attackers,moves1
00008|2A1DA1/1A4D/2A2A1/6A/3K3/3A3/7 a|3626|4340|crushing||-|1|kt||defenders,moves1
00009|1AA1D2/7/5A1/A6/1K4A/3A3/7 d|4140|5350|regicide||1|1|t||attackers,moves1
00010|1AA1D2/7/5A1/A6/K5A/5A1/7 d|0434|5550|regicide||1|1|t||attackers,moves1
00011|7/3A3/A2D3/2AKDAA/1D5/3A3/1A1A3 d|4145|5355|advantage||-|2|ct||attackers,moves1
00012|7/4A2/A2D3/2A1KAA/1A3D1/3D3/3A3 a|1404|3464|crushing||-|1|kt||defenders,moves1
00013|3A3/4D2/A6/2K2DA/2AA3/7/1A5 a|0301|3202|crushing||-|1|ckt|cornerFight|defenders,moves1
00014|1A5/1D5/A6/2K2DA/2AA3/7/1A5 a|0102|3234|crushing||-|3|k||defenders,moves1
00015|2A4/3A3/1D5/AAD1KDA/2D2A1/3A3/4A2 a|0212|3404|crushing||-|1|kt||defenders,moves1
00016|7/A3A2/1D5/AAD2DA/2D2A1/3AK2/4A2 a|1412|5404|crushing||-|1|kt||defenders,moves1
00017|7/A1A4/5D1/AAD2DA/2D2A1/3AK2/4A2 a|3161|5404|crushing||-|1|kt||defenders,moves1
00018|1A5/1AA4/D3D2/A2K2A/2DD1A1/3A3/3A3 a|5350|3303|crushing||-|1|kt||defenders,moves1
00019|1A5/1AA4/D3D2/A2K2A/2D1DA1/A6/3A3 a|4565|3303|crushing||-|1|kt||defenders,moves1
00020|5A1/1AD2A1/D6/D4AA/1K5/7/3A3 a|3646|4140|crushing||-|1|kt||defenders,moves1
00021|5A1/1A5/3D3/4DA1/1K4A/2A4/3A3 a|5262|4140|crushing||-|1|kt||defenders,moves1
00022|3A3/7/6D/A2KDAA/3D3/4A2/2DA3 a|3031|3313|crushing||-|3|kt||defenders,moves1
00023|7/2AA3/2D4/1D3AA/2A4/A6/2DKD2 a|1315|6303|crushing||-|1|k||defenders,moves1
00024|3A3/1DD4/4AAA/4K1A/7/2AA3/3D1A1 a|3656|3430|crushing||-|1|kt||defenders,moves1
00025|3A3/4D2/1A3D1/A1A3A/3K1A1/2D1A2/3A3 a|4544|4340|crushing||-|1|kt||defenders,moves1
00026|3A3/4D2/1A5/A1A3A/3KA2/2D1A2/3A1D1 a|3212|4340|crushing||-|1|kt||defenders,moves1
00027|3A3/2ADDA1/7/A1AK2A/6D/2D4/3A3 a|6353|1454|crushing||-|3|c||defenders,moves1
00028|2A4/A5A/4A2/3KD1A/1DD2A1/3A3/3A3 a|4546|3330|crushing||-|1|kt||defenders,moves1
00029|7/2A3A/1D2A2/2K3A/A2DA2/3A3/3A3 a|3626|3262|crushing||-|1|kt||defenders,moves1
00030|3A3/7/6D/AADKDAA/3D3/3A3/3A3 a|0301|3303|crushing||-|1|kt||defenders,moves1
00031|7/7/3ADD1/AADK2A/5D1/3A3/3A3 a|5343|3222|crushing||-|1|ct||defenders,moves1
00032|7/2DA3/5D1/A2K2A/3A1D1/7/3AD2 a|6361|6414|crushing||-|3|c||defenders,moves1
00033|2A4/3A3/1A4D/A1DKD1A/3D1A1/3A3/3A3 d|4344|5343|advantage||-|1|c||attackers,moves1
00034|2A4/1D1A3/2KD3/1A2DAA/3A3/4A2/3A3 a|3121|3431|crushing||-|1|ct||defenders,moves1
00035|2A4/2DA3/2KD3/D4AA/6A/1A5/3A3 a|1316|2220|crushing||-|1|kt||defenders,moves1
00036|2A4/1A1A3/1D4A/2AK3/2D1DA1/7/3DA2 a|3222|3330|crushing||-|1|kt||defenders,moves1
00037|4A2/5A1/2D2D1/A2K2A/3D3/2D2A1/3A3 a|6365|3303|crushing||-|1|kt||defenders,moves1
00038|4D2/3A3/3K1D1/AAA1AA1/4A2/3D3/7 a|4454|2343|crushing||-|3|k||defenders,moves1
00039|3A3/3A3/3D3/AADKDAA/2D4/3A3/2A4 a|5356|3363|crushing||-|1|kt||defenders,moves1
00040|7/2AA3/3D3/AA1KDAA/7/A1D4/3A3 a|3626|3343|crushing||-|1|kt||defenders,moves1
00041|1AA4/4A2/1K2A2/A5A/D4A1/7/3A3 a|3020|2151|crushing||-|1|kt||defenders,moves1
00042|1A1A3/6A/7/A1K2A1/3D2A/3A3/3AD2 a|5351|3262|crushing||-|1|ckt||defenders,moves1
00043|2A4/3A3/2D4/AADKDAA/3D3/3A3/3A3 a|1312|3303|crushing||-|1|kt||defenders,moves1
00044|2A4/7/3A3/2A2A1/D1AK3/2D1D2/3A3 a|2320|4346|crushing||-|1|kt||defenders,moves1
00045|7/3A3/2A2D1/AADK1A1/2D2A1/3A3/2A1D2 a|1316|3303|crushing||-|1|kt||defenders,moves1
00046|4D2/5DA/4A2/AADK1A1/2D4/3A3/2A2A1 a|6555|3303|crushing||-|1|kt||defenders,moves1
00047|2A1D2/7/1A1K1A1/2A4/2D1A2/2A4/4A2 a|3222|2333|crushing||-|3|k||defenders,moves1
00048|7/2AA3/1A4D/2D1KA1/A3D1D/3A3/3A3 a|6365|3404|crushing||-|1|kt||defenders,moves1
00049|3AD2/5A1/6D/AAD2KA/3D3/3A3/3A3 a|1512|3505|crushing||-|1|kt||defenders,moves1
00050|3A3/4A2/3KD1D/A6/1D5/3A3/1A2A2 a|6444|2322|crushing||-|1|kt||defenders,moves1
00051|2A4/3A3/1A1D3/3KDAA/D2A3/2D4/3A3 a|3646|3330|crushing||-|1|kt||defenders,moves1
00052|3A3/5A1/5D1/1ADKD2/5D1/1A5/3A3 a|3111|3454|crushing||-|4|t||defenders,moves1
00053|3A3/1A3A1/5D1/2D1D2/5D1/1A1K3/3A3 a|1505|5356|crushing||-|1|kt||defenders,moves1
00054|2A4/3A3/2D4/A1DKDAA/1A4D/3A3/4A2 a|1310|3303|crushing||-|1|kt||defenders,moves1
00055|2A4/3A3/2D4/5AA/A2K2D/4D2/2D1A2 a|3530|4341|crushing||-|3|kt||defenders,moves1
00056|3AD2/1A1A3/3D3/2AK1AA/5D1/2A4/3A3 a|6362|3363|crushing||-|1|kt||defenders,moves1
00057|7/4A2/3K3/A1D2AA/2A4/1A2A2/3A3 a|4252|2303|crushing||-|1|kt||defenders,moves1
00058|2A4/3AD2/1D1K3/AA4A/4D2/3A3/3A3 a|3151|2326|crushing||-|1|kt||defenders,moves1
00059|2A4/3AD2/1D1K3/AA4A/4D2/3A3/3A3 a|3632|2326|crushing||-|1|kt||defenders,moves1
00060|2A4/3A3/1A4D/A2KD1A/3D1A1/2DA3/3A3 a|1316|3303|crushing||-|1|kt||defenders,moves1
00061|3A3/7/1D4D/A2KD1A/3D3/3A3/2A4 a|3646|3313|crushing||-|3|kt||defenders,moves1
00062|3A3/1K1A3/2D4/A3D2/6A/7/1DA4 a|1312|2220|crushing||-|1|t||defenders,moves1
00063|7/3A3/1DA4/AADK1AA/3D3/3A3/3AD2 a|3565|3334|crushing||-|1|kt||defenders,moves1
00064|4A2/4A2/3D3/ADK2A1/3A1A1/2D4/3A3 a|4544|3202|crushing||-|1|kt||defenders,moves1
00065|7/2AD3/7/A1K2A1/4A2/2DD3/3A3 a|4414|3242|crushing||-|3|kt||defenders,moves1
00066|7/A1AA3/7/6A/1K5/2DD3/3A3 d|4161|6362|regicide||1|1|t||attackers,moves1
00067|7/1D5/1AA1A2/A1K1DA1/6A/6A/3A3 d|1110|3020|crushing||-|2|ct|cornerFight|attackers,moves1
00068|7/5D1/6A/A2KDA1/2AA3/6A/7 a|4262|3303|crushing||-|1|kt||defenders,moves1
00069|4D2/3A3/1DA4/2AK2A/1A1D2A/7/3D3 a|1312|3303|crushing||-|1|kt||defenders,moves1
00070|4D2/2A4/1D1A3/2AK2A/1A2D1A/7/2D4 a|4143|6242|crushing||-|1|c||defenders,moves1
00071|4D2/2A4/D2A3/2AK2A/3AD1A/7/2D4 a|2313|6242|crushing||-|1|c||defenders,moves1
00072|2A4/A6/4A2/A3K1A/6D/6D/2A4 a|1016|3464|crushing||-|1|kt||defenders,moves1
00073|2A4/4A2/A3D2/1A1KD1A/7/7/2D1D2 a|3132|3363|crushing||-|4|kt||defenders,moves1
00074|7/3A3/2A1A2/1A4A/1A3KD/7/2A2D1 d|4505|2404|regicide||1|1|t||attackers,moves1
00075|5A1/3A3/3D3/AA4A/7/1A3A1/2DKD2 a|1311|6404|crushing||-|1|c||defenders,moves1
00076|3A3/3A3/D1A4/1DD1D2/K5A/A6/3A3 a|0305|2021|crushing||-|1|||defenders,moves1
00077|2A1A2/2A4/2D4/AAD1D2/3K1A1/6A/3A3 a|4505|4346|crushing||-|1|ckt|cornerFight|defenders,moves1
00078|3A3/1A4A/2AK3/1AD2AA/4D2/7/3A3 a|6361|2363|crushing||-|1|kt||defenders,moves1
00079|4A2/3A3/3D1A1/AADKD1A/1D5/2A4/2A4 a|3626|3363|crushing||-|1|kt||defenders,moves1
00080|7/1AAA3/3D1D1/A1DK2A/1D3A1/3A3/3A3 a|4542|3334|crushing||-|3|kt||defenders,moves1
00081|7/2AA3/1D5/A1D1KA1/1D1D3/2A4/3A3 a|3010|3404|crushing||-|1|kt||defenders,moves1
00082|3A3/3A3/2D4/3K1AA/A2D3/1A4A/2D1D2 a|3545|3330|crushing||-|1|kt||defenders,moves1
00083|2A4/7/1A1AA2/AD1K1A1/2D4/2A1D2/3A3 d|5444|0232|crushing||-|1|c||attackers,moves1
00084|2A4/3A3/D6/2AK2A/D3DA1/7/3A3 a|3656|3336|crushing||-|1|kt||defenders,moves1
00085|2A4/3A3/D6/3KDAA/D6/2D1A2/1A1A3 a|6162|3331|crushing||-|4|kt||defenders,moves1
00086|7/3A1A1/2D4/1A1KD1A/1D5/2D4/2AAA2 a|3646|2221|crushing||-|3|ct||defenders,moves1
00087|7/7/1AA4/A1K1AA1/A2D3/3A1D1/3A3 d|3262|2161|regicide||1|1|t||attackers,moves1
00088|3A3/A6/7/A1D2KA/2D4/2A4/3AD2 a|0323|3505|crushing||-|1|kt||defenders,moves1
00089|2A4/4A2/3K3/1AD1DAA/2AD3/3A3/3A3 a|1413|2320|crushing||-|1|kt||defenders,moves1
00090|1AA4/3A3/4K2/D4AA/2ADD2/3A3/4A2 d|2426|1316|regicide||1|1|t||attackers,moves1
00091|7/A2A2D/2A2D1/1AD1K1A/5D1/4A2/3A3 a|6365|3404|crushing||-|1|kt||defenders,moves1
00092|7/A2AD2/4AD1/1ADK2A/5D1/4A2/5A1 a|3121|3363|crushing||-|1|kt||defenders,moves1
00093|7/A1D1D2/1A2AD1/3K2A/5D1/4A2/5A1 a|3626|3303|crushing||-|1|kt||defenders,moves1
00094|7/A1D2D1/1A2A1A/3K3/5D1/4A2/5A1 a|2161|3303|crushing||-|1|kt||defenders,moves1
00095|7/A1D1D2/4A1A/3K3/5D1/4A2/1A3A1 a|5451|3303|crushing||-|1|kt||defenders,moves1
00096|5A1/3A3/1AD4/3K1DA/1DDA1A1/7/3A3 a|0504|3330|crushing||-|1|kt||defenders,moves1
00097|2A4/A6/A6/2D3A/1A2A2/3KD2/2A2D1 a|4442|5303|crushing||-|1|kt||defenders,moves1
00098|1A2K2/7/3D3/A4AA/7/1A1A1A1/3A3 d|0405|0104|regicide||1|1|||attackers,moves1
00099|3A3/2D1A2/AD3A1/1A2D2/3K3/2AD2A/3A3 a|0302|4346|crushing||-|1|ckt|cornerFight|defenders,moves1
00100|2A4/7/A6/1AA4/3KA1A/4A1D/3AD2 d|4303|4404|regicide||1|1|t||attackers,moves1
00101|7/7/A1AA3/1D1K1AA/1D5/3A3/3AD2 a|3565|3334|crushing||-|1|kt||defenders,moves1
00102|7/7/A1AA3/1D1K2A/6D/3A3/3A1A1 a|5356|3334|crushing||-|3|kt||defenders,moves1
00103|7/7/A1AA3/1DK3A/7/6A/3A1A1 a|5651|3234|crushing||-|3|k||defenders,moves1
00104|2KA3/AD5/2A2A1/4D1A/3D3/3A3/1A1A3 d|1116|6101|regicide||1|1|||attackers,moves1
00105|3A3/2A4/1D5/A1AKDAA/2D4/2D1A2/3A3 a|6364|3363|crushing||-|1|kt||defenders,moves1
00106|3A3/7/1A2D2/A3KAA/3D3/7/3D3 a|0302|4345|crushing||-|3|t||defenders,moves1
00107|2D4/1A5/3A3/D2KA1A/D2A2D/7/7 a|4344|3363|crushing||-|1|kt||defenders,moves1
00108|3D3/7/1A1K3/A1D1DAA/3D3/4A2/3A3 a|6365|2326|crushing||-|1|kt||defenders,moves1
00109|7/7/1A1A1D1/2K3A/A6/2D1D2/3A3 a|3656|3202|crushing||-|1|kt||defenders,moves1
00110|5D1/4A2/1D1K3/A1D3A/1A1D1A1/7/3A3 a|4525|2303|crushing||-|1|kt||defenders,moves1
00111|3A3/2DA3/7/A1K1A2/1A5/7/3A3 a|4111|3242|crushing||-|3|kt||defenders,moves1
00112|3A3/1A1A3/7/A1K1A2/7/7/3A3 d|3222|3436|crushing||-|4|t||attackers,moves1
00113|3A3/1A1A3/2K4/A3A2/7/7/3A3 a|1323|2242|crushing||-|3|k||defenders,moves1
00114|3A3/1A1D3/7/AK3AA/7/3A1A1/3A3 a|3050|3130|crushing||-|1|kt||defenders,moves1
00115|3A3/7/2AD3/AA1K2A/2D4/7/2DAD2 a|3616|3336|crushing||-|1|kt||defenders,moves1
00116|7/1A5/6D/5AD/4AKD/4D2/3A3 a|1151|4555|crushing||-|3|kt||defenders,moves1
00117|2A4/3A3/7/AAD2AA/3KD2/1A5/3A3 a|5156|4454|crushing||-|3|t||defenders,moves1
00118|2A4/3A3/7/AAD1D1A/3K3/6A/3A1A1 a|0203|4346|crushing||-|1|ckt|cornerFight|defenders,moves1
00119|3AD2/3A3/7/AAD3A/3K3/5AA/3A3 d|4333|5505|crushing||-|1|ct||attackers,moves1
00120|2D1D2/2A4/7/AAK3A/7/5AA/3A3 a|6353|3262|crushing||-|1|kt||defenders,moves1
00121|2D4/2A1D2/7/AAK3A/7/3A1AA/7 a|5313|3262|crushing||-|1|kt||defenders,moves1
00122|3A3/7/AA1A3/A1K2A1/3D3/3A3/3AD2 d|3222|3565|crushing||-|1|ct||attackers,moves1
00123|3A3/2K4/AA1A3/A6/3D3/3A3/3A1A1 a|5356|1210|crushing||-|1|kt||defenders,moves1
00124|2A2A1/7/1A1A3/ADK1A2/3A3/4A2/7 a|0222|3262|crushing||-|1|kt||defenders,moves1
00125|3A3/3A2A/3D3/AADKDA1/D6/3A3/3A3 a|5350|334330404346|crushing||-|3|kt||defenders,moves2
00126|4A2/2DA3/A1D4/3KDAA/2D4/3A3/3A3 a|0402|3330|crushing||-|1|kt||defenders,moves1
00127|2A4/7/2D1D2/A5A/1A1KAA1/2A1D2/3A3 a|3646|4303|crushing||-|1|kt||defenders,moves1
00128|3A3/7/1A2DD1/A1DK2A/2D4/2A4/3A3 a|0323|3222|crushing||-|3|ct||defenders,moves1
00129|3A3/3A3/2A1D2/A2K2A/2A3D/4AA1/7 a|0302|3363|crushing||-|1|kt||defenders,moves1
00130|3A3/7/1AD1D2/A2K1AA/1D5/3A3/3A3 a|0323|3332|crushing||-|3|kt||defenders,moves1
00131|2A4/5D1/3A3/A1DK1DA/1AAA3/7/7 a|0222|3334|crushing||-|1|kt||defenders,moves1
00132|2A4/2D1D1A/7/AD1K2A/3D3/1A1A3/3A3 a|0203|3323|crushing||-|1|kt||defenders,moves1
00133|5A1/7/AA5/1AD4/D2A3/K2D3/2A4 d|4030|4340|regicide||1|1|ct||attackers,moves1
00134|7/1D1A3/1AAKD2/A3A1A/2AA3/7/7 a|4346|2363|crushing||-|1|kt||defenders,moves1
00135|2A4/3A3/2D4/AADKDAA/3D3/3A3/3A3 a|1311|3303|crushing||-|1|kt||defenders,moves1
00136|7/3A3/1ADKA2/1A2A2/1D5/3D3/4D2 a|3432|5352|crushing||-|3|t||defenders,moves1
00137|7/3A3/1ADKA2/1A5/2D4/3D3/4D2 a|3151|2333|crushing||-|3|k||defenders,moves1
00138|3A3/3A3/3D3/AAD1A2/3K2A/1A2D2/3A3 a|3050|4340|crushing||-|1|ckt|cornerFight|defenders,moves1
00139|2A4/3A3/3D3/1AD1A2/K5A/1A2D2/3A3 d|4050|4640|regicide||1|1|||attackers,moves1
00140|2A4/2A4/3D3/1AD1A2/6A/KA2D2/3A3 d|2324|4640|regicide||1|1|||attackers,moves1
00141|2A4/2A4/4D2/1AD1A2/6A/KA2D2/2A4 d|3222|4640|regicide||1|1|||attackers,moves1
00142|7/3A3/4A1D/2AK2A/4A2/3D3/1A5 a|4464|3343|crushing||-|3|kt||defenders,moves1
00143|7/3A3/7/6A/2AK1D1/2A1D2/4A2 a|1303|4323|crushing||-|3|k||defenders,moves1
00144|3A3/7/7/6A/2A2D1/2AKD2/4A2 a|3626|5333|crushing||-|3|k||defenders,moves1
00145|2A4/7/6A/7/A2K1D1/7/4A2 a|4010|4340|crushing||-|1|kt||defenders,moves1
00146|1AA4/3A1A1/3K3/A1D2A1/2D4/2A1D2/3A3 a|6364|2326|crushing||-|1|kt||defenders,moves1
00147|1AA4/3A3/1DD4/A2KDAA/2D4/4A2/3A3 a|6365|3363|crushing||-|1|kt||defenders,moves1
00148|3A3/4D2/1A1K3/AA5/1D3AD/2A4/3A3 a|5256|2326|crushing||-|1|kt||defenders,moves1
00149|7/1AA1D2/3A2A/1D5/3K1A1/2AD3/3A3 a|4535|4340|crushing||-|1|kt||defenders,moves1
00150|7/1A5/3A3/3K3/1D2DA1/3D2A/2AA3 a|6242|3330|crushing||-|1|kt||defenders,moves1
00151|1A5/7/1DA4/A2KDAA/2D4/1A1A3/3A3 a|2226|3303|crushing||-|1|kt||defenders,moves1
00152|7/3A3/2A1AD1/A2K1A1/2DDA2/1A1A3/7 a|3545|3336|crushing||-|1|kt||defenders,moves1
00153|4D2/3A1A1/2AK3/A5A/7/1AA4/3A3 a|6361|2363|crushing||-|1|kt||defenders,moves1
00154|4D2/3A3/A3D2/1A1K2A/3D3/3A3/2DA3 a|3634|4344|crushing||-|1|ct||defenders,moves1
00155|2D4/3A3/A3D2/1A1KA2/3D3/3A3/2DA3 a|1314|3303|crushing||-|1|kt||defenders,moves1
00156|7/D6/2D1A2/1A1KA2/3D3/3A3/3A3 a|2404|3303|crushing||-|1|kt||defenders,moves1
00157|4A2/D6/D6/1A1KA2/5D1/2A4/3A3 a|5232|3353|crushing||-|3|kt||defenders,moves1
00158|4A2/D6/D6/1AA1A2/3K1D1/7/3A3 a|6353|4535|crushing||-|3|c||defenders,moves1
00159|4A2/D6/D6/1AA2D1/7/3K3/3A3 a|6364|5356|crushing||-|1|kt||defenders,moves1
00160|4D2/3A3/3D3/1A3AA/A2K3/2D2A1/3A3 a|6364|4363|crushing||-|1|kt||defenders,moves1
00161|2AA1A1/7/3D3/A1D1K1A/1A1D3/3A3/2A4 a|4151|3404|crushing||-|1|ckt|cornerFight|defenders,moves1`;
