// AUTO-GENERATED by scripts/genpuzzles.ts — do not edit by hand.
// Regenerate: npx tsx scripts/genpuzzles.ts
// Placeholder: no puzzles yet. An empty fingerprint means the loader serves an
// empty bank under every ruleset, which is the correct behaviour for no data.
// Format: one line per puzzle, `id|pos|leadIn|line|goal|flags|dtm|depthToFind|salience|motif|tags`
// — see src/game/puzzleBank.ts for the exact contract.

export const BANK_RULES_FINGERPRINT: string = "";

export const BANK_BOARD_SIZE: number = 7;

export const BANK_VERIFY_DEPTH: number = 4;

export const BANK_DATA: string = ``;
