// Driven-browser assertions for the Nine Men's Morris surface.
//   npm run check:morris
//
// Sits beside tablut-smoke.mjs and copenhagen-smoke.mjs and copies their harness
// verbatim — server, browser discovery, init-script seeding — for the fourth
// time (ADR-0008 counts that as one of the costs of a fourth board). The reason
// it exists is the same and the things it can catch are not: the test suites are
// pure logic, so nothing in them can fail when a board made of points draws
// wrong.
//
// What can only break here:
//
//   • the board is **24 point targets**, named `a7 … a1` with `d7` at the top
//     middle. A square-lattice board that drew 49 cells, or a points table that
//     drifted from the indexing in game/morris/rules.ts, would look like a
//     plausible board and fail nothing in the suites;
//   • closing a mill enters a **removal step** that rings only the stones the
//     rules allow taking, ignores every other click, and completes the turn on
//     the removal. `removable()` has its own unit tests; whether the *board* lit
//     those stones is invisible to them;
//   • the engine's reply is *shown* on the point it went to — one worker, one
//     reply, one stone, in a real browser;
//   • Ballinderry is **KEPT** on this surface, with the stored choice untouched,
//     and the board draws 24 drilled holes under it. This is the exact inverse of
//     the assertion in tablut-smoke.mjs and copenhagen-smoke.mjs, and it is the
//     whole reason this check is worth its runtime: `morris.surface.v1` is
//     deliberately absent from index.html's hand-written fallback list, so that
//     list is no longer "the surfaces" but "the surfaces that fall Ballinderry
//     back" — and nothing at that call site says so (ADR-0008);
//   • a Morris game survives leaving the surface, coming back, and a full reload;
//   • the Brandubh save is byte-identical after the visit, and the game did not
//     land in another board's key;
//   • three-way mutual exclusion: opening any board closes the other two.
//
// Same Chromium discovery list as screenshot.mjs and the other smoke scripts;
// keep them in step.
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { extname, join, normalize } from "node:path";
import { chromium } from "playwright-core";

const DIST = new URL("../dist/", import.meta.url).pathname;
// playwright-core ships no browser of its own, so it always needs an explicit
// executable. Prefer CHROMIUM_PATH, then the sandbox's pre-provisioned build,
// then whatever the distro installed.
const CANDIDATES = [
  process.env.CHROMIUM_PATH,
  "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
  "/usr/bin/google-chrome-stable",
].filter(Boolean);
const CHROME = CANDIDATES.find((p) => existsSync(p));
if (!CHROME) {
  console.error("no Chromium found; set CHROMIUM_PATH. Tried:\n  " + CANDIDATES.join("\n  "));
  process.exit(2);
}
const MIME = {
  ".html": "text/html",
  ".js": "text/javascript",
  ".css": "text/css",
  ".otf": "font/otf",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".json": "application/json",
  ".gz": "application/gzip",
  ".bin": "application/octet-stream",
};

const server = createServer(async (req, res) => {
  try {
    let path = decodeURIComponent(new URL(req.url, "http://x").pathname);
    if (path === "/") path = "/index.html";
    const file = normalize(join(DIST, path));
    if (!file.startsWith(DIST)) throw new Error("escape");
    const body = await readFile(file);
    res.writeHead(200, { "content-type": MIME[extname(file)] ?? "application/octet-stream" });
    res.end(body);
  } catch {
    // SPA fallback: serve index.html for unknown routes.
    try {
      res.writeHead(200, { "content-type": "text/html" });
      res.end(await readFile(join(DIST, "index.html")));
    } catch {
      res.writeHead(404);
      res.end();
    }
  }
});

await new Promise((r) => server.listen(0, r));
const { port } = server.address();

const fails = [];
const check = (ok, what, detail = "") => {
  if (ok) console.log(`ok   ${what}`);
  else {
    console.error(`FAIL ${what}${detail ? ` — ${detail}` : ""}`);
    fails.push(what);
  }
};

/**
 * A mill-free placing phase as `SavedMove` triples (see game/morris/persist.ts):
 * `[from, to, remove]` with −1 for "none", so every one of these is a placement
 * that took nothing. Generated by walking the engine's own `allMoves` and taking
 * the first quiet move each time, which is what makes all eighteen legal by
 * construction rather than by hand. It leaves White to move with two moves
 * available — `c5-d5` and `c5-c4`.
 */
const MOVING_PHASE_MOVES = [[-1, 0, -1], [-1, 1, -1], [-1, 2, -1], [-1, 3, -1], [-1, 4, -1], [-1, 5, -1], [-1, 6, -1], [-1, 7, -1], [-1, 8, -1], [-1, 9, -1], [-1, 10, -1], [-1, 11, -1], [-1, 12, -1], [-1, 13, -1], [-1, 14, -1], [-1, 15, -1], [-1, 16, -1], [-1, 18, -1]];

const browser = await chromium.launch({ executablePath: CHROME });
const page = await browser.newPage({ viewport: { width: 860, height: 1400 } });
const pageErrors = [];
page.on("pageerror", (e) => pageErrors.push(e.message));
await page.addInitScript(() => {
  try {
    localStorage.setItem("brandubh.theme", "everforest");
    // Mark the first-visit board-preset step (src/boardPresets.ts) seen. A bare
    // Chromium context has no localStorage at all, which is exactly what that
    // step is gated on, so without this it opens over everything and swallows the
    // click below meant for the mode step. The other smoke scripts carry the same
    // line for the same reason; keep them in step.
    localStorage.setItem("brandubh.boardPresetSeen", "1");
    // Seeded rather than played out: a game to a real conclusion is not cheap in
    // a smoke check, and the module's own recording logic already has pure-test
    // coverage (src/game/aiResults.test.ts). This only has to prove the setup
    // sheet *reads* what is stored, under Morris's own key.
    localStorage.setItem(
      "morris.aiResults.v1",
      JSON.stringify([
        { rulesetId: "morris-gasser-1", difficulty: "ollamh", humanSide: "white", result: "win", endedAt: 1 },
        { rulesetId: "morris-gasser-1", difficulty: "ollamh", humanSide: "white", result: "win", endedAt: 1 },
        { rulesetId: "morris-gasser-1", difficulty: "ollamh", humanSide: "white", result: "draw", endedAt: 1 },
      ]),
    );
  } catch {
    /* localStorage unavailable */
  }
});
await page.goto(`http://localhost:${port}/`, { waitUntil: "networkidle" });

// ── A Brandubh game in progress, so there is a real save to protect ──────────
const otb = page.getByRole("button", { name: /with a friend in person/ });
await otb.waitFor();
await otb.click();
const start = page.getByRole("button", { name: "Start game" });
await start.waitFor();
await start.click();
const bboard = page.getByRole("grid", { name: "Brandubh board" });
await bboard.locator('[role=gridcell][aria-label^="d1"]').click();
await bboard.locator('[role=gridcell][aria-label^="c1"]').click();
await page.waitForTimeout(600);
const savedBefore = await page.evaluate(() => localStorage.getItem("brandubh.game.v1"));
check(savedBefore !== null, "a Brandubh game in progress is autosaved");

// ── The drawer's More games section ──────────────────────────────────────────
await page.getByTestId("menu-toggle").click();
await page.waitForSelector('[data-testid="app-drawer"]');
const more = page.getByTestId("drawer-more-games");
await more.waitFor();
await more.locator("summary").click();
check((await page.getByTestId("drawer-morris").count()) === 1, "More games lists Nine Men's Morris");
await page.getByTestId("drawer-morris").click();

// ── The setup sheet ──────────────────────────────────────────────────────────
const setupDialog = page.locator('.morris-screen [role="dialog"]');
await setupDialog.waitFor();

// The Custom rule editor must render. Copenhagen shipped a version of this that
// threw `undefined.map`, because the editor kept its own stale copy of another
// game's enum values — see ENUM_CHOICES in game/morris/variants.ts and
// ruleChoices.test.ts. A thrown render leaves the sheet showing nothing rather
// than crashing visibly, so the check counts the controls.
await setupDialog.locator("select").first().selectOption("custom");
const ruleEditor = setupDialog.locator(".rounded-lg.bg-black\\/20.p-3");
const segCount = await ruleEditor.locator(".seg").count();
check(segCount === 5, "the Custom editor renders one control per enum rule", `saw ${segCount}`);
check(
  (await ruleEditor.getByRole("button", { name: "At three stones" }).count()) === 1,
  "the enum controls are labelled from morrisRuleValues, not a tafl table",
);
// Back to the shipped preset, so the game below (and its export) names it.
await setupDialog.locator("select").first().selectOption("morris-gasser-1");

// All four tiers, none capped — the inverse of Copenhagen's tier cap, which
// belongs to that board's 11×11 search and not to the ladder.
for (const tier of ["Easy", "Medium", "Hard", "Ollamh"]) {
  const btn = setupDialog.getByRole("button", { name: tier, exact: true });
  check(!(await btn.isDisabled()), `the ${tier} tier is offered on this board`);
  check(
    (await btn.getAttribute("aria-disabled")) === null,
    `the ${tier} tier carries no aria-disabled`,
  );
}
check(
  (await setupDialog.getByText(/plays a small endgame perfectly/).count()) > 0,
  "the setup sheet states both halves of what Ollamh is",
);
check(
  (await setupDialog.getByText("Your record vs the computer:").count()) > 0,
  "the AI results label is shown",
);
check(
  (await setupDialog.getByText("Ollamh 2-0-1").count()) > 0,
  "the seeded Ollamh record renders as 2-0-1",
);

// ── Into a game against the engine, as White ──────────────────────────────────
// White, because White places first (`firstMove`): taking that seat is what puts
// the human on move and makes "two plies" mean "the human placed and the engine
// answered".
await setupDialog.getByRole("button", { name: "White", exact: true }).click();
await setupDialog.getByRole("button", { name: "Medium", exact: true }).click();
await setupDialog.getByRole("button", { name: "Play", exact: true }).click();
const mb = page.getByRole("group", { name: "Nine Men's Morris board" });
await mb.waitFor();

// ── The board: 24 points, named and placed per the fixed indexing ─────────────
const points = mb.locator('[data-testid="morris-point"]');
const pointCount = await points.count();
check(pointCount === 24, "the board has exactly 24 point targets", `saw ${pointCount}`);
const names = await points.evaluateAll((els) => els.map((el) => el.getAttribute("data-point")));
check(
  names.slice(0, 8).join(",") === "a7,d7,g7,g4,g1,d1,a1,a4",
  "the outer ring runs a7, d7, g7, g4, g1, d1, a1, a4",
  names.slice(0, 8).join(","),
);
check(new Set(names).size === 24, "all 24 points are distinctly named", `${new Set(names).size}`);
check(
  ["a7", "a4", "a1", "d7", "d1", "g7", "g1", "c5", "e3", "b4", "f4", "d6"].every((n) =>
    names.includes(n),
  ),
  "the three rings' points are all present, inner ring included",
);
// `d7` is the top middle in the unflipped view, which is the one placement the
// whole naming scheme turns on: the outer ring's top line is a7–d7–g7.
const cxOf = (name) =>
  mb.locator(`[data-point="${name}"] circle.morris-hit`).getAttribute("cx").then(Number);
const cyOf = (name) =>
  mb.locator(`[data-point="${name}"] circle.morris-hit`).getAttribute("cy").then(Number);
check((await cxOf("d7")) === 350 && (await cyOf("d7")) === 50, "d7 is drawn at the top middle");
check((await cxOf("a7")) === 50 && (await cyOf("a7")) === 50, "a7 is drawn at the top left");
check((await cxOf("g1")) === 650 && (await cyOf("g1")) === 650, "g1 is drawn at the bottom right");

const files = (await mb.locator(".morris-coord").allTextContents()).slice(0, 7).join("");
const ranks = (await mb.locator(".morris-coord").allTextContents()).slice(7).join(",");
check(files === "abcdefg", "the files run a-g along the bottom edge", files);
check(ranks === "7,6,5,4,3,2,1", "the ranks run 7 down to 1 up the left edge", ranks);

// ── A placement, and the engine's reply ───────────────────────────────────────
const movedTwice = () =>
  page
    .waitForFunction(
      () =>
        (document.querySelector(".morris-screen .playerbar-movecount")?.textContent ?? "") === "2",
      undefined,
      { timeout: 60000 },
    )
    .then(() => true)
    .catch(() => false);
const promptText = () => page.getByTestId("morris-prompt").innerText();
check((await promptText()).includes("Place a stone"), "the board asks for a placement");
const dots = await mb.locator(".morris-dot").count();
check(dots === 24, "every empty point is offered while placing", `saw ${dots}`);
await mb.locator('[data-point="d7"]').click();
check(
  (await mb.locator('[data-point="d7"][aria-label="d7 white"]').count()) === 1,
  "the placed stone lands on the point that was clicked",
);
check(await movedTwice(), "the engine replies from its worker (bottom seat shows 2 moves)");

// Its stone is *shown*: exactly one black stone, on a named point, visible rather
// than held hidden under a copy that never arrived.
const blacks = await points.evaluateAll((els) =>
  els
    .filter((el) => (el.getAttribute("aria-label") ?? "").endsWith(" black"))
    .map((el) => el.getAttribute("data-point")),
);
check(blacks.length === 1, "the engine placed exactly one stone", blacks.join(","));
const engineStone = mb.locator(`[data-point="${blacks[0]}"] .morris-stone.is-black`);
check(await engineStone.isVisible(), `the engine's stone is shown on ${blacks[0]}`);
check(
  (await mb.locator(".morris-stone.in-flight").count()) === 0,
  "no stone is left hidden once the reveal has settled",
);

// Zen off, which is also how a player reaches the flip controls and the stats
// strip (both are Zen extras / hidden in Zen).
await page.locator('.morris-screen [data-testid="morris-zen-toggle"]').click();
const strip = page.getByTestId("morris-inhand");
check((await strip.innerText()).includes("White 8"), "the stats strip counts the stones in hand");
check(
  (await page.locator(".morris-screen").getByText("Placing").count()) > 0,
  "the stats strip names the phase",
);

// ── Flip ──────────────────────────────────────────────────────────────────────
const openGameMenu = async () => {
  // Scoped to the surface: the Brandubh shell's own bottom toolbar is still in
  // the DOM behind this overlay and shares the same testid.
  await page.locator('.morris-screen [data-testid="toolbar-menu"]').click();
  await page.waitForSelector('[data-testid="game-menu"]');
};
await openGameMenu();
await page.getByRole("menuitem", { name: "Flip board left-right" }).click();
check(
  (await cxOf("a7")) === 650,
  "flip left-right mirrors where a7 is drawn, not what it is called",
  `cx ${await cxOf("a7")}`,
);
check(
  (await mb.locator('[data-point="a7"]').getAttribute("aria-label")) === "a7",
  "a flipped board still calls the point a7",
);
await openGameMenu();
await page.getByRole("menuitem", { name: "Flip board left-right" }).click();
check((await cxOf("a7")) === 50, "flip left-right toggles back");
const flipStored = await page.evaluate(() => [
  localStorage.getItem("morris.boardFlipped"),
  localStorage.getItem("morris.boardFlippedV"),
]);
check(
  flipStored[0] === "0",
  "the flip preference persists under Morris's own key",
  JSON.stringify(flipStored),
);

// ── Game file: download, round trip, and a refusal ────────────────────────────
await openGameMenu();
await page.getByRole("menuitem", { name: "Game file (.morris)" }).click();
const gfModal = page.getByTestId("morris-gamefile-modal");
await gfModal.waitFor();
const [download] = await Promise.all([
  page.waitForEvent("download"),
  gfModal.getByRole("button", { name: "Download" }).click(),
]);
const downloadPath = await download.path();
const exported = downloadPath ? await readFile(downloadPath, "utf8") : "";
check(exported.includes('[Format "morris-1"]'), "the exported file carries the Morris format tag");
check(
  download.suggestedFilename().endsWith(".morris"),
  "the download is a .morris file, not a .tafl one",
  download.suggestedFilename(),
);
check(/\[Variant "morris-gasser-1"\]/.test(exported), "the exported file names the variant");

const gameIdBefore = await page.evaluate(
  () => JSON.parse(localStorage.getItem("morris.game.v1") ?? "{}").id,
);
// Paste the same export straight back in — a round trip, not a different game.
await gfModal.getByLabel("Open a game file").fill(exported);
await gfModal.getByRole("button", { name: "Load game" }).click();
await gfModal.waitFor({ state: "detached" });
check(await movedTwice(), "importing the exported file round-trips the game (2 moves)");
const gameIdAfter = await page.evaluate(
  () => JSON.parse(localStorage.getItem("morris.game.v1") ?? "{}").id,
);
check(
  typeof gameIdAfter === "string" && gameIdAfter !== gameIdBefore,
  "the imported game gets a fresh identity rather than continuing the old one",
);

// A malformed file must show the same error copy every other panel shows.
await openGameMenu();
await page.getByRole("menuitem", { name: "Game file (.morris)" }).click();
await gfModal.waitFor();
await gfModal.getByLabel("Open a game file").fill('[Format "morris-1"]\n\n1. z9 z9\n');
await gfModal.getByRole("button", { name: "Load game" }).click();
const gfError = gfModal.getByTestId("import-error");
check(await gfError.isVisible(), "a malformed file shows the existing error copy");
check(
  (await gfError.innerText()).includes("something in the move list is not a move"),
  "the error copy names what was wrong",
);
await gfModal.getByRole("button", { name: "Close" }).click();
await gfModal.waitFor({ state: "detached" });

// ── The removal step ─────────────────────────────────────────────────────────
// Driven in hotseat, deliberately: the engine's own replies are not scripted, so
// the only way to reach a *chosen* mill in a fixed number of clicks is to play
// both sides. White takes the outer ring's top line a7–d7–g7 while Black sits on
// b6 and b4 — neither of which is in a mill, so both are legal victims and the
// ring count is the assertion.
await openGameMenu();
await page.getByRole("menuitem", { name: "New game" }).click();
await setupDialog.waitFor();
await setupDialog.getByRole("button", { name: "Two players", exact: true }).click();
await setupDialog.getByRole("button", { name: "Play", exact: true }).click();
await mb.waitFor();
for (const point of ["d7", "b6", "g7", "b4"]) await mb.locator(`[data-point="${point}"]`).click();
await page.waitForFunction(
  () => (document.querySelector(".morris-screen .playerbar-movecount")?.textContent ?? "") === "4",
  undefined,
  { timeout: 10000 },
);
await mb.locator('[data-point="a7"]').click();

check((await promptText()).includes("A mill!"), "closing a mill asks for a stone to take");
const ringed = await mb.locator(".morris-removable").evaluateAll((els) =>
  els.map((el) => el.closest("[data-point]")?.getAttribute("data-point")),
);
check(
  ringed.sort().join(",") === "b4,b6",
  "only the stones the rules allow taking are ringed",
  ringed.join(","),
);
check(
  (await page.evaluate(
    () => document.querySelector(".morris-screen .playerbar-movecount")?.textContent,
  )) === "4",
  "the mill-closing move is not committed until a stone is chosen",
);
check(
  (await mb.locator('[data-point="a7"][aria-label="a7 white"]').count()) === 1,
  "the stone that closed the mill is shown where it was placed",
);
// Every other click is ignored rather than guessed at.
await mb.locator('[data-point="g1"]').click();
check(
  (await page.evaluate(
    () => document.querySelector(".morris-screen .playerbar-movecount")?.textContent,
  )) === "4",
  "a click on a point this mill may not take does nothing",
);
await mb.locator('[data-point="b6"]').click();
await page.waitForFunction(
  () => (document.querySelector(".morris-screen .playerbar-movecount")?.textContent ?? "") === "5",
  undefined,
  { timeout: 10000 },
);
check(true, "the removal click completes the atomic move (5 moves)");
check(
  (await mb.locator('[data-point="b6"]').getAttribute("aria-label")) === "b6",
  "the stone it took is gone from the board",
);
check(
  (await page.locator(".morris-screen").getByText("a7xb6").count()) > 0,
  "the move log names the turn and its victim",
);
check((await mb.locator(".morris-removable").count()) === 0, "the removal step closes behind it");

// ── Back out; the Brandubh game must be exactly as it was ─────────────────────
await page.getByRole("button", { name: "Back", exact: true }).click();
await bboard.waitFor();
const bcols = await bboard.evaluate(
  (el) => getComputedStyle(el).gridTemplateColumns.split(/\s+/).filter(Boolean).length,
);
check(bcols === 7, "the Brandubh board is 7 columns again", `saw ${bcols}`);
const savedAfter = await page.evaluate(() => localStorage.getItem("brandubh.game.v1"));
check(savedAfter === savedBefore, "the Brandubh save is untouched by the Morris visit");
const otherKeys = await page.evaluate(() => [
  localStorage.getItem("tablut.game.v1"),
  localStorage.getItem("copenhagen.game.v1"),
  localStorage.getItem("morris.game.v1"),
]);
check(otherKeys[0] === null && otherKeys[1] === null, "the Morris game did not land in another board's key");
check(otherKeys[2] !== null, "the Morris game landed in its own key");

// ── Back in: the game must have survived the visit out ────────────────────────
await page.getByTestId("menu-toggle").click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-morris").click();
await mb.waitFor();
check(
  (await page.getByRole("button", { name: "Play", exact: true }).count()) === 0,
  "re-entry resumes the saved game with no setup sheet in the way",
);
const movedFive = () =>
  page
    .waitForFunction(
      () =>
        (document.querySelector(".morris-screen .playerbar-movecount")?.textContent ?? "") === "5",
      undefined,
      { timeout: 20000 },
    )
    .then(() => true)
    .catch(() => false);
check(await movedFive(), "the five moves survived leaving the surface");

// ── Reload: the surface itself persists, and so does the game ─────────────────
await page.reload({ waitUntil: "networkidle" });
const mbAfterReload = page.getByRole("group", { name: "Nine Men's Morris board" });
const surfaceSurvived = await mbAfterReload
  .waitFor({ timeout: 10000 })
  .then(() => true)
  .catch(() => false);
check(surfaceSurvived, "a reload lands back on the Morris surface");
if (surfaceSurvived) {
  check(await movedFive(), "the game survived the reload");
  check(
    (await mb.locator('[data-point="a7"][aria-label="a7 white"]').count()) === 1,
    "the replayed position is the one that was saved",
  );
}

// ── Ballinderry is KEPT here — the inverse of the two bigger tafl boards ──────
// Ballinderry draws a board of drilled holes traced back to a real 7x7 peg board
// (docs/ballinderry-board.md). On the 9x9 and the 11x11 that is a lie about the
// board and `resolveTheme` falls it back; on 24 points sitting on the same 7x7
// lattice it is truthful, so it stays — `applyTheme` is deliberately not told
// about this surface and `morris.surface.v1` is deliberately absent from
// index.html's pre-paint list (ADR-0008). Both halves are checked: the painted
// theme, and the holes actually drawn.
const paintedTheme = () => page.evaluate(() => document.documentElement.dataset.theme);
const storedTheme = () => page.evaluate(() => localStorage.getItem("brandubh.theme"));
const visibleHoles = () => page.locator('.morris-board [data-testid="morris-hole"]:visible').count();

check((await visibleHoles()) === 0, "no drilled holes are drawn under an ordinary theme");

await page.addInitScript(() => {
  try {
    localStorage.setItem("brandubh.theme", "ballinderry");
  } catch {
    /* localStorage unavailable */
  }
});
await page.reload({ waitUntil: "networkidle" });
await mb.waitFor();
const onSurface = await paintedTheme();
check(onSurface === "ballinderry", "Ballinderry is kept on the Morris surface", `saw ${onSurface}`);
check(
  (await storedTheme()) === "ballinderry",
  "…and the stored theme choice is of course untouched",
);
const holes = await visibleHoles();
check(holes === 24, "the board draws one drilled hole per point under Ballinderry", `saw ${holes}`);
check(
  (await page.evaluate(
    () => document.documentElement.dataset.theme,
  )) === "ballinderry",
  "the pre-paint script leaves Morris's theme alone (its surface key is not in that list)",
);

// Leaving for the 7x7 board keeps it, and visiting Copenhagen still loses it —
// the rule the other scripts pin, re-checked from here so a change to one is
// never mistaken for a change to both.
await page.getByRole("button", { name: "Back", exact: true }).click();
await bboard.waitFor();
check((await paintedTheme()) === "ballinderry", "Ballinderry paints on the Brandubh board too");

// ── Three-way mutual exclusion ───────────────────────────────────────────────
// ADR-0008's measured cost: three boolean flags, three pairs to keep exclusive,
// every mount gate naming the others. src/App.mutualExclusion.test.ts covers the
// corrupted-storage half; this is the half that needs real clicks.
// A reload while on a boardgame surface also resets App's own showModeOverlay
// state to its default (on) — that state knows nothing about which surface is
// showing — so the Ballinderry section's reload-while-on-Morris left a resume
// prompt quietly stacked *underneath* the Morris screen (DOM order, not
// visibility, decided who was on top). Backing out just now revealed it. Resolve
// it the way a real player would, before using the hamburger beneath. The
// Copenhagen script carries the same block for the same reason.
const staleResume = page.getByRole("button", { name: "Resume game" });
if (await staleResume.isVisible().catch(() => false)) {
  await staleResume.click();
  await bboard.waitFor();
}

const mountedSurfaces = async () => {
  const [tablut, copenhagen, morris] = await Promise.all([
    page.locator(".tablut-screen").count(),
    page.locator(".copenhagen-screen").count(),
    page.locator(".morris-screen").count(),
  ]);
  return { tablut, copenhagen, morris };
};

await page.getByTestId("menu-toggle").click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-morris").click();
await mb.waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 0, morris: 1 }),
  "Morris is the only surface mounted",
);

// Morris → Tablut, from inside Morris's own hamburger.
await page.locator('.morris-screen [data-testid="menu-toggle"]').click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-tablut").click();
await page.getByRole("grid", { name: "Tablut board" }).waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 1, copenhagen: 0, morris: 0 }),
  "opening Tablut from inside Morris closes Morris",
);
// Tablut has no game from this script, so it opened on its own setup sheet; its
// backdrop blocks its header, so play "Two players" purely to get past it.
await page.getByRole("button", { name: "Two players" }).click();
await page.getByRole("button", { name: "Play", exact: true }).click();

// Tablut → Morris.
await page.locator('.tablut-screen [data-testid="menu-toggle"]').click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-morris").click();
await mb.waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 0, morris: 1 }),
  "opening Morris from inside Tablut closes Tablut",
);

// Morris → Copenhagen → Morris.
await page.locator('.morris-screen [data-testid="menu-toggle"]').click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-copenhagen").click();
await page.getByRole("grid", { name: "Copenhagen Hnefatafl board" }).waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 1, morris: 0 }),
  "opening Copenhagen from inside Morris closes Morris",
);
const cphSetup = page.locator('.copenhagen-screen [role="dialog"]');
if (await cphSetup.count()) {
  await cphSetup.getByRole("button", { name: "Two players", exact: true }).click();
  await cphSetup.getByRole("button", { name: "Play", exact: true }).click();
}
await page.locator('.copenhagen-screen [data-testid="menu-toggle"]').click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-more-games").locator("summary").click();
await page.getByTestId("drawer-morris").click();
await mb.waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 0, morris: 1 }),
  "opening Morris from inside Copenhagen closes Copenhagen",
);

// The setup overlay closes every board surface, Morris included.
await page.locator('.morris-screen [data-testid="menu-toggle"]').click();
await page.waitForSelector('[data-testid="app-drawer"]');
await page.getByTestId("drawer-new-game").click();
await page.waitForSelector('[data-testid="mode-overlay-close"]');
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 0, morris: 0 }),
  "opening the setup overlay from the drawer closes every boardgame surface",
);
await page.getByTestId("mode-overlay-close").click();
await bboard.waitFor();
check(
  JSON.stringify(await mountedSurfaces()) === JSON.stringify({ tablut: 0, copenhagen: 0, morris: 0 }),
  "cancelling the setup overlay leaves none of them open",
);
check(
  (await page.evaluate(() => localStorage.getItem("morris.surface.v1"))) === null,
  "leaving the surface clears its flag",
);

// ── The moving phase: a step, and the engine's stone *travelling* ─────────────
// Seeded rather than played: eighteen placements is eighteen clicks and a lot of
// engine waiting, and what this section is for is the one thing that only exists
// once both hands are empty — a stone that *moves*. The save is a mill-free
// placing phase (generated from the engine's own move list, so every ply is
// legal by construction), with White to play and exactly two moves available.
//
// The travel is worth a driven-browser check for the same reason
// `npm run check:ai-reveal` exists for the square boards: a copy of the stone
// that renders but never translates, or a real stone that appears on its point
// immediately with a decoration flying in beside it, look identical to a correct
// reveal in any screenshot and fail nothing in the suites. (The second of those
// was a real bug in this board's first cut.)
await page.evaluate((moves) => {
  const now = Date.now();
  localStorage.setItem("morris.surface.v1", "1");
  localStorage.setItem(
    "morris.game.v1",
    JSON.stringify({
      v: 1,
      id: "moving-phase",
      createdAt: now,
      savedAt: now,
      variantId: "morris-gasser-1",
      customRules: {},
      playMode: "white",
      difficulty: "medium",
      moves,
      status: "playing",
      cursor: moves.length,
      recorded: false,
      clock: null,
      match: null,
      gamesPerSet: 1,
      names: { p1: "", p2: "" },
    }),
  );
}, MOVING_PHASE_MOVES);
await page.reload({ waitUntil: "networkidle" });
await mb.waitFor();
check(
  (await page.locator(".morris-dot").count()) === 0,
  "nothing is offered until a stone is picked up in the moving phase",
);
await mb.locator('[data-point="c5"]').click();
check(
  (await mb.locator(".morris-selected").count()) === 1,
  "clicking your own stone selects it",
);
const stepDots = await mb.locator(".morris-dot").count();
check(stepDots === 2, "a selected stone offers exactly its two empty neighbours", `saw ${stepDots}`);
// The flight has to be watched for *before* the move that provokes it: the
// engine answers this position in a moment and the stone is only in the air for
// half a second, so a check that starts after the reply has landed can never see
// it. `waitForFunction` polls on animation frames, which is fast enough.
const inFlight = page
  .waitForFunction(
    () =>
      document.querySelector(".morris-mover") !== null &&
      document.querySelector(".morris-stone.in-flight") !== null,
    undefined,
    { timeout: 60000 },
  )
  .then(() => true)
  .catch(() => false);
await mb.locator('[data-point="d5"]').click();
check(
  (await mb.locator('[data-point="d5"][aria-label="d5 white"]').count()) === 1,
  "a step along a line is played by click, then click",
);
check(await inFlight, "the engine's stone travels: a copy in flight, the real one waiting under it");
// Caught mid-flight, the copy is drawn *away* from the point the move went to —
// which is the whole difference between a stone that travels and a stone that
// teleports with a decoration beside it. The transition returns it to the
// identity transform, i.e. to its destination, and it is taken down there.
const travelled = await page.evaluate(() => {
  const mover = document.querySelector(".morris-mover");
  return mover ? getComputedStyle(mover).transform : "gone";
});
const offset = /matrix\(1, 0, 0, 1, (-?[\d.]+), (-?[\d.]+)\)/.exec(travelled);
check(
  !!offset && (Number(offset[1]) !== 0 || Number(offset[2]) !== 0),
  "…and while it travels it is drawn away from the point it is going to",
  travelled,
);

// Then it lands: the copy comes down, the real stone shows on the point the move
// went to, and the point it came from stays lit.
await page.waitForSelector(".morris-mover", { state: "detached", timeout: 10000 });
const log = await page.locator(".morris-screen ol li").last().innerText();
const token = log.replace(/^\d+\.\s*/, "").trim();
check(/^[a-g][1-7]-[a-g][1-7]/.test(token), "the engine's reply is a step", token);
const [fromName, toName] = token.replace(/x.*$/, "").split("-");
check(
  (await mb.locator(`[data-point="${toName}"]`).getAttribute("aria-label")) === `${toName} black`,
  `the engine's stone landed on ${toName}`,
);
check(
  await mb.locator(`[data-point="${toName}"] .morris-stone.is-black`).isVisible(),
  "the landed stone is shown rather than left hidden under a copy that is gone",
);
check(
  (await mb.locator(`[data-point="${fromName}"] .morris-origin`).count()) === 1,
  `the point it came from is left lit (${fromName})`,
);

check(pageErrors.length === 0, "no uncaught page errors", pageErrors.join(" | "));

await browser.close();
server.close();
if (fails.length) {
  console.error(`\n${fails.length} check(s) failed`);
  process.exit(1);
}
console.log("\nall Morris checks passed");
